### ISSUE TITLE
Discord tag is now invalid

### ISSUE THREAD

**Issue by Ruuku420** [Red-Spectre/Info#1]
Due to the recent changes in discords tag system, Tapood#6952 no longer is a reachable tag.

**Comment by Red-Spectre** [comment]
Hey there, 
We updated the repo to link to our new website. If you want to reach out, feel free to do it there (https://theredspectre.com/contact-us.html)

In retrospect this should have been done sooner, but time constraints and hectic circumstances prevented us from doing so.
